### ISSUE TITLE
Can't use Offset Animation

### ISSUE THREAD

**Issue by 9chip6** [mrachinskiy/commotion#13]
I use blender 3.0 and 2.93. My version's addon is 2.2.0. 
While i press Offset Animation. The error pop up and i don't know what it is. Please help.
![3](https://user-images.githubusercontent.com/86162823/122648987-e0455e80-d155-11eb-9e9b-77bbcdf7ef73.png)

**Comment by mrachinskiy** [comment]
Your objects have empty material slots, remove them or assign a material. Meanwhile I will work on a proper fix for this issue.

**Comment by mrachinskiy** [comment]
Thanks for the report, this issue will be fixed in 2.2.1 release.

**Comment by 9chip6** [comment]
Thank you.
