### ISSUE TITLE
Error trying to enable add-on (Blender 2.93, Commotion 2.2.1)

### ISSUE THREAD

**Issue by czarzhan** [mrachinskiy/commotion#14]
When I try to enable the add-on, I get this error:
![image](https://user-images.githubusercontent.com/386913/123852072-e4a61000-d8e9-11eb-9af6-a9a7ee3f2fb6.png)

**Comment by czarzhan** [comment]
I apologize if this issue has already been addressed. I'm not familiar with this reporting system and am not sure how to look up past issues/fixes.

**Comment by mrachinskiy** [comment]
Download add-on using link from the [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).
