### ISSUE TITLE
Unable to install in Blender 2.93

### ISSUE THREAD

**Issue by AKMDesigner** [mrachinskiy/commotion#16]
When i try to enable it it shows some kind of error. Below is the attached screenshot.
![Screenshot (577)](https://user-images.githubusercontent.com/87749809/126444441-f2d3b0f7-dcdd-44c6-a950-11e29ace7aa4.png)

**Comment by mrachinskiy** [comment]
Download add-on using link from the [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

**Comment by AKMDesigner** [comment]
I followed the same steps but that;s still not working

**Comment by mrachinskiy** [comment]
You are not downloading the add-on release, you downloading add-on repository, to install add-on you have to download release by using link from installation guide.

**Comment by AKMDesigner** [comment]
Thanks buddy for the help
