### ISSUE TITLE
Traceback error with commotion addon

### ISSUE THREAD

**Issue by MiaDarling93** [mrachinskiy/commotion#18]
I have been trying to install commotion to recreate the book animation. Although the add-on is installed, I am unable to enable and use the add-on. I have received a traceback error that says FileNotFound. Can anyone help me with this issue?
![Screenshot 2021-09-29 052638](https://user-images.githubusercontent.com/51015418/135168426-b7f76b50-0b08-493e-ab72-e90ba08bab22.jpg)
.

**Comment by mrachinskiy** [comment]
Download add-on using link from the [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

**Comment by MiaDarling93** [comment]
Thank you very much :)
