### ISSUE TITLE
Commotion Blender Add-on

### ISSUE THREAD

**Issue by Baasis** [mrachinskiy/commotion#2]
Установил аддон, но он не включается, показывает ошибку.
[https://pp.vk.me/c626317/v626317298/227f4/7GoDrB1_K6w.jpg](Скриншотl)

**Comment by mrachinskiy** [comment]
Спасибо за баг репорт, по непонятной причине последний commit push не учёл все изменения в модуле.
Исправленно коммитом b3bc6fb8b7d17fa5b10b7b0ca0aa01ac8af3e3ae

**Comment by Baasis** [comment]
Вау! Как быстро.Большое спасибо. Все работает.Сделал пост в группе и раскидал по соседним Пост 20.08.2016, 19:46, "Mikhail Rachinskiy" <notifications@github.com>:Спасибо за баг репорт, по непонятной причине последний commit push не учёл все изменения в модуле.Исправленно коммитом b3bc6fb—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С уважением,Инженер конструктор первой категорииНИЦ "Техностандарт"+7-951-5005-117
