### ISSUE TITLE
Can't enable commotion as an addon in preferences Blender 3.0.1

### ISSUE THREAD

**Issue by Goofbean** [mrachinskiy/commotion#22]
I installed the commotion master version by following the guide: downloading the zip and selecting it when clicking on Install in the addon menu. I didn't unzip the file.

The addon shows up, but when i click the checkbox to enable it I get this error:

<img width="588" alt="blender_AWTMPtq54r" src="https://user-images.githubusercontent.com/39836649/159924198-aed0d090-fb5c-47ba-9cea-1a2963baea76.png">

Version is 3.0.1

Let me know how to solve this!

**Comment by mrachinskiy** [comment]
You are trying to install add-on repository instead of release. Make sure you download add-on release using link provided in step one of this guide.
