### ISSUE TITLE
Selected Key or Range Feature Request

### ISSUE THREAD

**Issue by rbergeron3d** [mrachinskiy/commotion#24]
Hello!
I love how simple Commotion is to use and can add life to an animation, but in more complex scene, I would like to have the control on which keys I would apply the offset. As of now, as it applies the offset on the whole timeline, it breaks some of the other Animation I have in my shots. Do you think that would be simple to implement?

Thanks a lot and let me know if you need more info (If you are interested in this request)

Ray

**Comment by mrachinskiy** [comment]
Thanks for feedback, I think it should be trivial to implement selection only offset.
At the moment I do not have time for it, but I will add it to the list of planned features and come back to it when I can.
