### ISSUE TITLE
Can't copy NLA strip to another object in blender 3.1

### ISSUE THREAD

**Issue by Akikannblossom** [mrachinskiy/commotion#25]
Here is what I have encountered:
 I want to use the Animation Utils function to copy a NLA strip to another object in blender 3.1, when I hit the copy button, the bug happened. This function is alright in previous blender version. 

the error code as follows:
Python: Traceback (most recent call last):
  File "C:\Users\51598\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\commotion\ops_anim.py", line 116, in execute
    self.nla_copy(ob, Anim.nla_tracks_ob)
  File "C:\Users\51598\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\commotion\ops_anim.py", line 172, in nla_copy
    strip_new = track_new.strips.new(strip.name, strip.frame_start, strip.action.copy())
TypeError: NlaStrips.new(): error with argument 2, "start" -  Function.start expected an int type, not float

location: <unknown location>:-1

**Comment by mrachinskiy** [comment]
Thank you for the report! Fix will be available in the next release.
