### ISSUE TITLE
erro add Blender 3.4.1

### ISSUE THREAD

**Issue by MFN69** [mrachinskiy/commotion#29]
A favor, this adds doesn't work for blender 3.4.1 would there be a way that you could fix it, so that it works for this version of blender. Thank you so much.
--------------------------------------------------------------------------

(https://user-images.githubusercontent.com/123533474/235329814-1b675e78-6938-460a-82f2-b4389a833118.jpg)

![Screenshot_error adds](https://user-images.githubusercontent.com/123533474/235329839-ae45805e-dbe6-4af0-b60e-347e0bbcd51e.jpg)

Image
https://prnt.sc/DApsIQCNyBpT

**Comment by mrachinskiy** [comment]
If error occurs on add-on activation, it means you are trying to install add-on repository instead of release. Make sure you download add-on release using link provided in [step one of installation guide](https://github.com/mrachinskiy/commotion#how-to-install).
