### ISSUE TITLE
[Suggestion] Add option to offset Drivers ID-Block

### ISSUE THREAD

**Issue by RazorWolvendom** [mrachinskiy/commotion#33]
Object Target: (Object name.001...)
![ScreenShot_20231209183922](https://github.com/mrachinskiy/commotion/assets/44827474/4ff84b53-7add-48c7-992e-d2935fcb3f8b)

**Comment by mrachinskiy** [comment]
What value exactly is supposed to be offsetted here?

**Comment by RazorWolvendom** [comment]
> What value exactly is supposed to be offsetted here?

a Material value (Emission for example)

**Comment by mrachinskiy** [comment]
It's controlled by the driver, it cannot be offsetted. The driver's expression has to be modified with additional offset value, I'm not sure it is a good thing to do.

Do you have a specific use case?

**Comment by RazorWolvendom** [comment]
> It's controlled by the driver, it cannot be offsetted. The driver's expression has to be modified with additional offset value, I'm not sure it is a good thing to do.
> 
> Do you have a specific use case?

no no, the offset happens on the object target, so like if you got a driver with cube.001 all other cubes would have that same driver with the same object target. the option would swap the object target based on the same name

what i want is to make all those drivers use its next object name (just as the name preset works) to make like Cube.002 having a driver with object target cube.002 and cube 003 has a driver with object target cube.003 and so on...
because the offset already was made with the animated position, those drivers only inspects the objects location to change the **Material value** based on that

**Comment by mrachinskiy** [comment]
If I understand correctly, you want to set target object property of a driver variable to current object?

I'm not sure it's in the scope of the add-on, and then there are other issues:
* How to decide which variable to set, and which to ignore in case drive have multiple variables?
* How to handle Distance and Rotational Difference variables?

At this point GN simulation zone might be a better tool. Drivers were not designed to do stuff like this.

**Comment by RazorWolvendom** [comment]
> If I understand correctly, you want to set target object property of a driver variable to current object?
> 
> I'm not sure it's in the scope of the add-on, and then there are other issues:
> 
> * How to decide which variable to set, and which to ignore in case drive have multiple variables?
> * How to handle Distance and Rotational Difference variables?
> 
> At this point GN simulation zone might be a better tool. Drivers were not designed to do stuff like this.

i see
