### ISSUE TITLE
Unable to add commotion add on

### ISSUE THREAD

**Issue by Dreadbear19** [mrachinskiy/commotion#35]
I tried dropping, it, downloading it to blender but can't seem to find the add on. Can someone help please

**Comment by mrachinskiy** [comment]
Which version of Blender do you have? Where from you tried to download the add-on?

**Comment by mrachinskiy** [comment]
Could you please specify a website instead of giving bing search results?

**Comment by Dreadbear19** [comment]
https://extensions.blender.org/add-ons/commotion/

Sorry I meant to add this
________________________________

**Comment by mrachinskiy** [comment]
These extensions are strictly for Blender 4.2, update your blender version and you can install commotion right from the Blender > Preferences > Get Extensions.

If you cannot update to 4.2, then use [installation guide for 4.1](https://github.com/mrachinskiy/commotion?tab=readme-ov-file#how-to-install)

**Comment by Dreadbear19** [comment]
Hello,

It’s works now after upgrading blender, thanks!


________________________________
