### ISSUE TITLE
distributed selected keyframes unexpectedly

### ISSUE THREAD

**Issue by mrmrrr** [mrachinskiy/commotion#36]
Hey i have multiple objects with many keyframes and i want to use commotion only on portion of that and i found this problem:

if there are keyframes before the selected ones, they are aligned only if the indicator on the timeline is on the first keyframe
![1](https://github.com/user-attachments/assets/25becaa8-e885-453c-b65b-13d691897326)

also if keyframes before selected ones distributed randomly, it's distributed selected keyframes unexpectedly
![2](https://github.com/user-attachments/assets/e42ada82-7f5e-49a8-b25f-85fad378bd0f)

**Comment by mrachinskiy** [comment]
> if there are keyframes before the selected ones, they are aligned only if the indicator on the timeline is on the first keyframe

That is because animation length takes into account all keyframes. I need to think about this behavior.

> also if keyframes before selected ones distributed randomly, it's distributed selected keyframes unexpectedly

This behavior also depends on the whole length of the animation, rather than selected. Yeah, that one needs to be changed.

**Comment by mrachinskiy** [comment]
Fixed, update your add-on to version 4.2.1
