### ISSUE TITLE
Offset results in random keyframe positions that ignore the set parameters

### ISSUE THREAD

**Issue by Default0X** [mrachinskiy/commotion#37]
I've been using the addon for roughly a year now and it's been working really well for me, but of recent I noticed a problem that I can't understand.

When I try to keyframe a simple animations, with lesser surrounding keyframes, it works fine. No  problems there.
The problems come from when I try to keyframe more populated timelines, with more keyframes, it just ignores my set parameters and places the keyframes at odd locations.

No matter the parameters I set, the result will always be the same.
I'd love if this can be addressed.
Thank you

https://github.com/user-attachments/assets/4d258f78-b1f7-4c3a-980e-042be4bf95eb

**Comment by mrachinskiy** [comment]
Please share blend file with the issue so I can reproduce it.

**Comment by Default0X** [comment]
Alright
I can't share this exact file since it's a client's work, but I can reproduce it and share it with you 
Just give me a moment

**Comment by Default0X** [comment]
Ok so I couldn't recreate the exact problem, so I just stripped the file of any important aspects and modified the models.
But the problem is still the same.

I can't attach the file here so I linked it.
https://www.dropbox.com/scl/fi/6ewmvfebj5ys16s243xgw/Commotion-addon-troubleshoot.blend?rlkey=zr0dyb84683zj8dd1ekjqp8b8&dl=0

**Comment by mrachinskiy** [comment]
Working as expected, have you test the file you sent to me?

https://github.com/user-attachments/assets/753b2768-d9a9-4dc6-85b3-a5e90611aa17

**Comment by mrachinskiy** [comment]
Which version of Commotion do you have?

To test if there is interference, use `File` > `Defaults` > `Use Factory Settings`, then enable only Commotion and try again.

**Comment by Default0X** [comment]
Just did that, still no luck 🫠
I literally cleared my blender config file and just started with a fresh blender (after backing up of course), but the results didn't change

https://github.com/user-attachments/assets/16eb1609-cd71-4e94-99df-a3015be6fbbc

**Comment by mrachinskiy** [comment]
You still didn't tell me version of Commotion you are using.

**Comment by Default0X** [comment]
Oh, my bad
Commotion 2.4.0
Blender 4.1.1

**Comment by mrachinskiy** [comment]
Update to the newest version of Commotion 2.4.1 and test it again.

**Comment by Default0X** [comment]
Would that be compatible with blender 4.1.1?
I can't update my blender yet. 
It may break some things amongst the team. So we're sticking with 411 for now. 
Can I use 2.4.1 on 411?

**Comment by mrachinskiy** [comment]
Yes, you can use 2.4.1 with Blender 4.1, it's stated in the installation guide.

**Comment by Default0X** [comment]
Ok, I'm trying to do that now, but after downloading it form [https://extensions.blender.org/add-ons/commotion/], and trying to install it the normal way, I got an error saying "ZIP packaged incorrectly; __init__.py should be in a directory, not at top-level
"

So I tried to extract it and place it in a folder then extract it again. When I tried installing it again, I didn't get an error, but the addon didn't install properly either since nothing showed up in the addons menu

**Comment by Default0X** [comment]
Hey mrachinskiy
Thanks for your help
I managed to get the addon installed and everything works as expected now

**Comment by mrachinskiy** [comment]
> Ok, I'm trying to do that now, but after downloading it form [https://extensions.blender.org/add-ons/commotion/], and trying to install it the normal way, I got an error saying "ZIP packaged incorrectly; **init**.py should be in a directory, not at top-level "

extensions.blender.org is for Blender 4.2, you have to download Commotion from GitHub to use in Blender 4.1 and earlier.

> I managed to get the addon installed and everything works as expected now

Nice.
