### ISSUE TITLE
Error while installing addon

### ISSUE THREAD

**Issue by cobalt8888** [mrachinskiy/commotion#6]
![error](https://user-images.githubusercontent.com/74255292/102691051-0a02e480-420a-11eb-935b-bb233f3897fa.jpg)

**Comment by mrachinskiy** [comment]
Please follow [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

**Comment by cobalt8888** [comment]
I know How to install addons, I even unistall all addons, then close Blender, then install this addon again and nothing. Same message. "already registered as a subclass" probably means that part of this addon already installed, but its not true. Installed on Blener 2.9 and 2.91 and same message again and again.
Please help. 
BTW this message was generated AFTER addon instalation And blender cant initialize it.

**Comment by mrachinskiy** [comment]
This error message is useless, it tell that it is already registered and cannot be registered a second time.
To get an actual error message you have to close Blender, then open it, active add-on and send me the error massage that was generated.

**Comment by cobalt8888** [comment]
![error1](https://user-images.githubusercontent.com/74255292/102699429-e3ae6a80-4244-11eb-99d9-2df13e720988.jpg)

error massage  in jpg

**Comment by mrachinskiy** [comment]
The issue is that you are installing add-on repository instead of release. Use [installation guide](https://github.com/mrachinskiy/commotion#how-to-install), it has link to release download.

**Comment by cobalt8888** [comment]
Thank you very much - now it works. 
Merry Christmas :)
