### ISSUE TITLE
Enabling Addon Commotion

### ISSUE THREAD

**Issue by johannesgrewer** [mrachinskiy/commotion#7]
Hey!

My version number: commotion-2_2_0
Blender version: 2.92
Whenever I try to enable your addon I'll get this error:

![grafik](https://user-images.githubusercontent.com/8958268/110947980-1a29ec00-8341-11eb-88e7-4be3d7c44cc7.png)

Hope you can help!

Best regards,
Johannes

**Comment by mrachinskiy** [comment]
Have you tried closing and reopening Blender again?
If issue is still present, them make sure to reload Blender and make a screenshot of the error first time it appears.

**Comment by johannesgrewer** [comment]
Yeah, just tried. Getting the same error.

**Comment by johannesgrewer** [comment]
![grafik](https://user-images.githubusercontent.com/8958268/110950684-6d516e00-8344-11eb-96d4-39e7c3c1df68.png)

You mean reloading like restarting? Or donwloading a whole new version of blender?

**Comment by mrachinskiy** [comment]
I pretty sure I know what it is, you did not download add-on using link provided in [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

**Comment by johannesgrewer** [comment]
![grafik](https://user-images.githubusercontent.com/8958268/110952863-f9649500-8346-11eb-95f0-08b0a19e42c7.png)
I clicked this link....?

**Comment by mrachinskiy** [comment]
Click the link that says "Download" right next to it.

**Comment by johannesgrewer** [comment]
![grafik](https://user-images.githubusercontent.com/8958268/110953427-a3442180-8347-11eb-9c7e-bcdb75f080fb.png)

Yep, I downloaded it from exactly there :)

**Comment by mrachinskiy** [comment]
You did not. In error message screenshot it is specifically stated that you downloaded add-on repository instead of release.
Please completely remove previous instance of Commotion and use link provided in installation guide.

**Comment by johannesgrewer** [comment]
Ah, yeah, I tried to download it few weeks ago and used the wrong link. Think somewhere could be some remnants of that... Will take  alook.
