### ISSUE TITLE
Не включается аддон

### ISSUE THREAD

**Issue by ValSem1967** [mrachinskiy/commotion#8]
Добрый день скачал аддон Commotion. При включении выдает ошибку.
![Error](https://user-images.githubusercontent.com/81912184/113510811-3d714100-9565-11eb-84e1-f69f91cb8fca.png)

**Comment by mrachinskiy** [comment]
Загрузите аддон по ссылке указанной в первом шаге [инструкции по установке](https://github.com/mrachinskiy/commotion#установка).

**Comment by ValSem1967** [comment]
Большое вам спасибо!  Аддон включился. Не ожидал такой быстрой поддержки. Супер!
