### ISSUE TITLE
Addon doesn't activate

### ISSUE THREAD

**Issue by NizarAmous** [mrachinskiy/commotion#9]
Hello,

Thanks for your addon, it's very usefull. 

My problem is that i couldn't activate the latest version, im on linux mint, you can see the error message on the screenshot, same problem on blender 2.92 and on master 3.0

![image](https://user-images.githubusercontent.com/45922048/116633303-0b2ee580-a951-11eb-8a6a-9eb1ac2b4ed8.png)

Hope you can find a solution, thank you

**Comment by mrachinskiy** [comment]
Download add-on using link from the [installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

**Comment by NizarAmous** [comment]
It worked, thank you ! the one that we download from here is not the same 
![image](https://user-images.githubusercontent.com/45922048/116699736-d5741600-a9bd-11eb-8852-5d7c924fa7b5.png)
